### PR TITLE
Queue claim block modification tasks to prevent loss

### PR DESCRIPTION
**Pull request by ProdPreva1l**
Solves: #100

### CODE REVIEW

**Comment by WiIIiam278** [comment]
oh you've cooked here, will take a look tmrw if I get time :)

**Comment by ProdPreva1l** [comment]
Pretty simple just a concurrent queue polling every 2 ticks

**Comment by WiIIiam278** [comment]
only Q is -- will this actually work?

`getPlugin().fireClaimBlocksChangeEvent` is fired within this runnable and this method itself fires a sync, then an async task to dispatch the event and do async stuff on the DB afterwards. it's feasable this still leaves a race condition..potentially?

**Comment by ProdPreva1l** [comment]
I have tested and it no longer occurs by spamming the command like it used to.

**Comment by ProdPreva1l** [comment]
The issue was something weird todo with the "polling rate" and some desync.

**Pull request merged**
