### PR TITLE
Add a WorldGuard hook

### PR DESCRIPTION
**Pull request by Emibergo02**
Do not overlap HuskClaims claims on Worldguard regions
I would have liked to make a WorldGuard flag like the one on HuskTowns 
but RedisClaims hooks don't implement a method called by JavaPlugin onLoad()
and WorldGuard allows flags registration only on plugin load phase

### CODE REVIEW

**Comment by WiIIiam278** [comment]
Failing locale tests - can you fix this by adding the new locale to the other three files?

**Comment by Emibergo02** [comment]
Ok I don't know russian or romanian but google translate will help me XD

**Comment by ProdPreva1l** [comment]
You should 100% to make it a flag, just have a peep how i did it in towns to get an idea, its a bit tedious but is alot nicer

**Comment by WiIIiam278** [comment]
After discussion, we're putting this on ice while we look at a better way of doing hooks to support this :)

**Pull request closed without merging**
